#!/bin/bash

if [ -z $1 ]
then 
SCRIPT_DIR=~/.bin
SOURCE_DIR=~/.src/kaliboulat
else
SCRIPT_DIR=~/bin
SOURCE_DIR=~/src/kaliboulat
fi

SCRIPT_FILE=$SCRIPT_DIR/Kaliboulat

mkdir -p $SCRIPT_DIR
cat <<EOF >$SCRIPT_FILE
#!/bin/bash

LOGDIR=~/.log/Bullk
mkdir -p \$LOGDIR
DATE=\$( date +%Y%m%d-%H%M%S )

$SOURCE_DIR/Kaliboulat &> \$LOGDIR/Kaliboulat.\$DATE.log
EOF

chmod 700 $SCRIPT_FILE

pushd $SOURCE_DIR
git pull
#make clean
make

popd
